---
title: "Project Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Predictive Model for Mines Park Fault

#### Diego Curbelo and Brighton Garrett

##### Abstract:

##### Introduction: 
This data was taken from a case study at mines park. This study looked at a decentralized treatment facility that requires vigilant monitoring to
mitigate risks to system, human, and environmental health. It consists of 43,552 measurements of 42 variables that were taken every 10 minutes from April 10, 2010 at 6:10 AM to May 11, 2010 at 5:00 AM. The observations showed a fault in the system that is displayed in Figure 1. When the pH drops below the blue line, it is no longer safe for the  In this figure, there is a large decrease in the pH and it had to go through three different additions of a buffer solution to recover. The purpose of our work is to find a model that will detect a fault of this sort earlier than it happens. To do this we looked at the of the pH of the water with the other 41 different models. We found the variables that had a good correlation and used this as an indicator for when the pH is going to suddenly drop which would alert the facility. 

##### Methods:

##### Results:

##### Discussion:
